name: Build & check formatting

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        rust:
          - stable
        include:
          - os: ubuntu-latest
            rust: 1.63.0
          - os: ubuntu-latest
            rust: nightly
    steps:
      - uses: actions/checkout@v4
      - run: |
          cargo build --release

  check-rustfmt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          cargo fmt --check

  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          cargo test
